config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :fish_orders, only: [:destroy] do
    member do
      get "add"
      get "remove"
      post "email-order"
    end
  end

  resources :restaurants, only: [:index, :show, :new, :create] do

    resources :fish_orders, only: [:new, :create] do
    end

    member do
      get "my_restaurant", constraints: lambda { |req| User.find(req.session["warden.user.user.key"].first.first).restaurant.id == req.params[:id].to_i }
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://static.pexels.com/photos/61153/fish-fischer-ocean-market-61153.jpeg');">
  
  <div class="banner-content">
    <h1 class="headline">Connecting <%= typing @array %></h1>
    <button class="btn-banner" data-toggle="modal" data-target="#modalSignUp">SIGN UP</button>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('<%= photo?(restaurant) %>');">

  <div class="card-body">
    <div class="card-category text-center">
      <% compare(restaurant) %>
      <% if !@intersection.empty? %>
          <h4><%= @intersection.size %></h4>
          <%= image_tag "fish_solid.png", class: "card-icon" %>
          <h5>MATCH</h5>
      <% else %>
          <h4></h4>
      <% end %>
    </div>

    <div class="card-desc">
      <h2><%= restaurant.name %></h2>
    </div>
  </div>
</div>

app/views/shared/_filter.html.erb
<div class="col-xs-12">
  <div id="filter-container">
    <h3>This is filter</h3>
  </div>
</div>

app/views/shared/_fish_order_fields.erb
<%= simple_form_for [restaurant, fish_order], :url => email_order_fish_order_path, method: :post do |form| %>
<div id= class="checkout-form-inputs">
  <%= form.input :weight_in_grams, label: false, collection: (1..fish_order.weight_in_grams).to_a, selected: fish_order.weight_in_grams %>
  <p>kg of <%= fish_order.fish.name %></p>
</div>
<%= form.submit value: "Email Restaurant", class: "btn-solid" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
<% end %>
<% if alert %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    &copy; seaBay
  </div>
</div>

app/views/shared/_map_box.html.erb
<div class="map_box text-center">
  <h3><%= restaurant.name %></h3>
  <h4>Is looking for</h4>
  <hr class="top-line">
  <% restaurant.fish_orders.each do |fish_order| %>
    <p><%= fish_order.weight_in_grams %> kg of <%= @fish[fish_order.fish_id] %> </p>
  <% end %>
    <hr class="bottom-line">
  <%= link_to "Details", restaurant_path(restaurant), class: "btn-solid" %>
</div>

app/views/shared/_navbar.html.erb
<!-- If user is signed in -->
<% if user_signed_in? %>
    <div class="navbar-wagon">
      <!-- Logo -->
      <div class="navbar-left">
        <%= image_tag "logo.png", class: "navbar-logo" %>
        <%= link_to "seaBay", restaurants_path, class: "navbar-wagon-brand" %>
      </div>
      <!-- If user is a restaurant owner -->
      <% if is_restaurant_owner? %>
        <!-- Right Navigation -->
        <div class="navbar-wagon-right hidden-xs hidden-sm">

          <!-- Links when logged in -->
          <%= link_to "My Restaurant", my_restaurant_restaurant_path(is_restaurant_owner?), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

          <!-- Avatar with dropdown menu -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
              <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        <!-- If user is NOT a restaurant owner -->
        <% else %>

          <!-- Right Navigation -->
        <div class="navbar-wagon-right hidden-xs hidden-sm">

          <!-- Links when logged in -->
          <%= link_to "Register Restaurant", new_restaurant_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Log-Out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

          <!-- Avatar with dropdown menu -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
              <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        <% end %>
      <!-- If user is NOT sign-in -->
      <% else %>
      <!-- Login link (when logged out) -->
      <div class="navbar-wagon">
    <!-- Logo -->
        <div class="navbar-left">
          <%= image_tag "logo.png", class: "navbar-logo" %>
          <%= link_to "seaBay", root_path, class: "navbar-wagon-brand" %>
        </div>
    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <button class="navbar-wagon-item navbar-wagon-link btn-nav" data-toggle="modal" data-target="#modalSignIn">Sign In</button>
      <button class="navbar-wagon-item navbar-wagon-link btn-nav" data-toggle="modal" data-target="#modalSignUp">Sign Up</button>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="modalSignIn" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg modal-container" role="document">

    <div class="modal-content modal-container-left text-center intro";">
      <h2>Log in to seaBay</h2>
      <p>Log in and sell your fish directly to restaurants in your area</p>
    </div>


    <div class="modal-content modal-container-right">
      <div class="navbar">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>

      <div class="modal-body">
        <%= render "shared/sign_in" %>
      </div>
    </div>

  </div>
</div>




<div class="modal fade" id="modalSignUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg modal-container" role="document">

    <div class="modal-content modal-container-left text-center intro";">
      <h2>Join seaBay</h2>
      <p>Sign up and sell your fish directly to restaurants in your area</p>
    </div>

    <div class="modal-content modal-container-right">
      <div class="navbar">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>

      <div class="modal-body">
        <%= render "shared/signup" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sign_in.html.erb
<div class="form">
  <div class="text-center">
    <h4 class="text-center">Sign in</h4>
  </div>
  <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-inputs">
        <%= f.input :email, label: false, placeholder: "Email", required: false, autofocus: true %>
        <%= f.input :password, label: false, placeholder: "Password", required: false %>
        <%= f.input :remember_me, inner_html: { class: 'Remember' }, as: :boolean if devise_mapping.rememberable? %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Log in", class: "btn-block" %>
      </div>

  <% end %>

    <%- if devise_mapping.omniauthable? %>
      <%- resource_class.omniauth_providers.each do |provider| %>
          <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), {class: 'btn-block btn-fb'}  %><br />
      <% end -%>
  <% end -%>

    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end -%>
  </div>
</div>

app/views/shared/_signup.html.erb
<div class="form">
  <div class="text-center">
    <h4 class="text-center">Sign Up</h4>
  </div>
  <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :email, label: false, placeholder: "Email",  required: false, autofocus: true, inner_html: { class: 'username' } %>
        <%= f.input :password, label: false, placeholder: "Password", required: false %>
        <%= f.input :password_confirmation, placeholder: "Confirm Password", label: false, required: false %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Sign up", class: 'btn-block' %>
      </div>
  <% end %>

    <%- if devise_mapping.omniauthable? %>
      <%- resource_class.omniauth_providers.each do |provider| %>
          <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), {class: 'btn-block btn-fb'}  %><br />
      <% end -%>
  <% end -%>
  <%- if controller_name != 'sessions' %>
      <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end -%>
</div>