config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :fish_orders, only: [:destroy] do
    member do
      get "add"
      get "remove"
      post "email-order"
    end
  end

  resources :restaurants, only: [:index, :show, :new, :create] do

    resources :fish_orders, only: [:new, :create] do
    end

    member do
      get "my_restaurant", constraints: lambda { |req| User.find(req.session["warden.user.user.key"].first.first).restaurant.id == req.params[:id].to_i }
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :fish_orders, dependent: :destroy
  accepts_nested_attributes_for :fish_orders, reject_if: :all_blank, allow_destroy: true
  has_many :fishes, through: :fish_orders

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :phone_number, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy, :my_restaurant]
  before_action :authenticate_user!
  def index

    flash.now[:notice] = "You order has been correctly added" if params[:notice].present?

    @restaurants = Restaurant.where.not(latitude: nil, longitude: nil)
    if search_params.empty?
      @restaurants
      @f = "Press the button to search for fish"
    else
      @fish = Fish.all
      search = search_params.to_h
      fish = search.select { |key, value| value == "1" }
      @f = []
      fish.keys.each { |name| @f << Fish.where(name: name).first }
      @restaurants = []
      @f.each do |fish|
        @fishorders = []
        if FishOrder.where(fish_id: fish.id).all
          @fishorders << FishOrder.where(fish_id: fish.id).all
          @fishorders.first.select do |order|
            @restaurants << order.restaurant
          end
        end
      end
    end
  
    @restaurants = @restaurants.uniq


    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow render_to_string(partial: "/shared/map_box", locals: { restaurant: restaurant })
    end
  end

  def show
    @fish = Fish.order("name asc")
    @fishorder = FishOrder.new
  end

  def new
    if params[:term]
      response = yelp_search(params[:term], params[:location])
      @restaurants = response["businesses"]

      @restaurant = Restaurant.new(
        name: @restaurants.first["name"],
        address: @restaurants.first["location"]["display_address"].join(" "),
        phone_number: @restaurants.first["phone"],
        email: current_user.email,
        img_url: @restaurants.first["image_url"],
        url: @restaurants.first["url"]
        )
    else
      @restaurants = []
      @restaurant = Restaurant.new
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to my_restaurant_restaurant_path(@restaurant.id)
    else
      # GO BACK TO THE FORM
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to :back
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def my_restaurant
    @fish = Fish.order("name asc")
    @fishorder = FishOrder.new
     @fish = Fish.order("name asc")
      @fishorder = FishOrder.new
      flash[:alert] = "YOU'RE NOT AUTHORIZED TO INITIATE A DUEL UNTIL YOU BECOME A NINJA, BUT YOU CAN BE INVITED TO A DUEL" if params[:alert].present?
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :email, :img_url, :url, :term, :location, fish_orders_attributes: [:id, :weight_in_grams, :done, :_destroy])
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def search_params
    @fish = Fish.all.map { |fish| fish.name.to_sym }
    params.permit(@fish)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def compare(restaurant)
    @orders = []
    @search = []
    restaurant.fish_orders.each { |order| @orders << order.fish_id }
    @fishes = Fish.all
    match_params = params.select { |key, value| value == "1" }
    fish_hash = match_params.each { |fish| fish }
    fish_hash.select do |key, value|
      fish_object = Fish.where(name: key)
      @search << fish_object.first.id
    end
    @intersection = @orders & @search
    @intersection
  end
end

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<div class="main-container">
  <div class="container">
    <div class="index-container">
      <div class="index-left">
        <div class="filter-names">
          <div class="tags">
            <% if @f.class == String %>
                <p id="instuctions">Use filter to find what restaurants are looking for </p>
            <% else %>
            <% @f[0,4].each do |fish| %>
              <div class="btn-solid-pill"><p><%= fish.name %></p></div>
                <% end %>
                    <% if @f.count > 4 %>
                        <div class="btn-solid-pill"><p>+ <%= @f.count - 4 %></p></div>
                    <% end %>
            <% end %>
          </div>
          <button type="button" class="btn-search" data-toggle="modal" data-target="#fishes">
            Filter by fish
          </button>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="fishes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Select your fish</h4>
              </div>

              <div class="modal-body">
                <div class="filters">
                  <%= simple_form_for "", url: restaurants_path, html: { class: "filter"}, method: :get do |f| %>
                      <% @fish.sort! %>
                      <% @fish.each do |fish| %>
                          <div class="checkbox">
                            <%= f.input fish, as: :boolean, input_html: { class: "fish_name", checked: params[fish].to_i == 1 }, html: { class: "slider round" }, label_html: { class: 'switch' } %>
                          </div>
                      <% end %>
                </div>
              </div>

              <div class="modal-footer filter-inputs">
                <%= f.submit 'Search for Match' %>
                <%= link_to "Clear filters", restaurants_path, class: "stupid-button" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="restaurants">
          <div class="row">
            <% sorted = @restaurants.sort {|a,b| compare(b).size<=>compare(a).size } %>
            <% sorted.each do |c| %>
              <%= link_to restaurant_path(id: c.id) do %>
                <div class="col-xs-12 col-sm-6">
                  <%= render 'shared/card', restaurant: c %>
                </div>
            <% end %>
          <% end %>
          </div>
        </div>
      </div>
      <div class="map-right">
        <div id="map">
        </div>
      </div>
    </div>
  </div>





  <% content_for(:after_js) do %>
    <script>

      var styles = [
    {
        "featureType": "administrative",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#6195a0"
            }
        ]
    },
    {
        "featureType": "administrative.province",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "geometry",
        "stylers": [
            {
                "lightness": "0"
            },
            {
                "saturation": "0"
            },
            {
                "color": "#f5f5f2"
            },
            {
                "gamma": "1"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "all",
        "stylers": [
            {
                "lightness": "-3"
            },
            {
                "gamma": "1.00"
            }
        ]
    },
    {
        "featureType": "landscape.natural.terrain",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.park",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#bae5ce"
            },
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
            {
                "saturation": -100
            },
            {
                "lightness": 45
            },
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#fac9a9"
            },
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "labels.text",
        "stylers": [
            {
                "color": "#4e4e4e"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#787878"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "labels.icon",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "transit.station.airport",
        "elementType": "labels.icon",
        "stylers": [
            {
                "hue": "#0a00ff"
            },
            {
                "saturation": "-77"
            },
            {
                "gamma": "0.57"
            },
            {
                "lightness": "0"
            }
        ]
    },
    {
        "featureType": "transit.station.rail",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#43321e"
            }
        ]
    },
    {
        "featureType": "transit.station.rail",
        "elementType": "labels.icon",
        "stylers": [
            {
                "hue": "#ff6c00"
            },
            {
                "lightness": "4"
            },
            {
                "gamma": "0.75"
            },
            {
                "saturation": "-68"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
            {
                "color": "#eaf6f8"
            },
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#c7eced"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "lightness": "-49"
            },
            {
                "saturation": "-53"
            },
            {
                "gamma": "0.79"
            }
        ]
    }
]

      var handler = Gmaps.build('Google');
      handler.buildMap({
        provider: {
          styles: styles
        },
        internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    </script>
  <% end %>
</div>

app/views/restaurants/my_restaurant.html.erb
<div class="top-container">
  <div class="top-container-left">
    <div class="description">
      <h2><%= @restaurant.name %></h2>
      <p><%= @restaurant.address %></p>
      <p><%= @restaurant.phone_number %></p>
      <p><%= @restaurant.email %></p>
    </div>

  </div>
  <div class="top-container-right img-fluid">
      <%= image_tag @restaurant.img_url %>
  </div>
</div>
<div class="text-center">
  <div class="fish-form">
    <p><%= Time.now.strftime("%A, %B %C, %G") %></p>
    <h3>Today we're looking for</h3>
    <%= simple_form_for([@restaurant, @fishorder]) do |f| %>
        <div class="yelp-search">
          <div class="fish-form-inputs">
            <%= f.input :weight_in_grams, label: false, prompt: "kg", collection: (1..10).to_a %>
            <%= f.input :fish_id, label: false, prompt: "Fish", collection: @fish %>
            <%= f.submit value: "Add" %>
            <%= link_to "Order complete", restaurants_path(notice: true) %>
          </div>

        </div>
    <% end %>
  </div>
</div>
<div class="fish-cards">
    <% @restaurant.fish_orders.each do |order| %>
        <div class="fish-card">
          <div class="fish-card-info">
            <h4><%= order.fish.name %></h4>
            <p><%= order.weight_in_grams %> kg</p>
          </div>
          <div class="fish-card-exit">
            <span class="plus-minus"><%= link_to image_tag("delete-icon.png", border: 0, class: "icon"), fish_order_path(order.id), method: :delete, data: {confirm: "Delete this order?"} %></span>
          </div>
        </div>
    <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="wrapper">
  <div class="form-container">
    <div class="upper-form form-inline text-center">
          <h2>Add your Restaurant</h2>
          <h5>Autofill your restaurant profile through Yelp</h5>
        <div class="form-search">
          <%= form_tag(new_restaurant_path, method: :get) do %>
              <div class="yelp-search">
                <div class="restaurant-form-inputs">
                  <%= text_field_tag :term, nil ,placeholder: "Restaurant Name" %>
                  <%= text_field_tag :location, nil ,placeholder: "City" %>
                  <%= submit_tag 'Search', class: "yelp-button", value: "FIND WITH YELP" %>
                </div>
              </div>
          <% end %>
        </div>
    </div>
    <div class="form">
      <%= simple_form_for(@restaurant) do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <p>Name</p>
            <%= f.input :name, label: false, placeholder: "Full Name", required: false %>
            <p>Address</p>
            <%= f.input :address, label: false, placeholder: "Address", required: false %>
            <p>Phone Number</p>
            <%= f.input :phone_number,  label: false, placeholder: "Phone Number", required: false %>
            <%= f.input :email, as: :hidden %>
            <%= f.input :img_url, as: :hidden %>
            <%= f.input :url, as: :hidden %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Register Restaurant", class: "btn-block" %>
          </div>
      <% end %>

    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="top-container">
  <div class="top-container-left">
    <div class="description">
      <h2><%= @restaurant.name %></h2>
      <p><%= @restaurant.address %></p>
      <p><%= @restaurant.phone_number %></p>
      <p><%= @restaurant.email %></p>
    </div>

  </div>
  <div class="top-container-right" style="background-image: url('<%= photo?(@restaurant) %>');">
  </div>
</div>

<div class="bottom-container">
  <div class="bottom-container-left">
    <div class="fish-cards">
      <% @restaurant.fish_orders.each do |order| %>
      <%= link_to add_fish_order_path(order.id), remote: true, id: "like_#{order.id}" do %>
      <div class="fish-card">
        <div class="fish-card-info">
          <h4><%= order.fish.name %></h4>
          <p><%= order.weight_in_grams %> kg</p>
        </div>
        <div class="fish-card-exit">
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="bottom-container-right">
    <div id="checkout">
    </div>
  </div>
</div>